//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.18 at 12:46:08 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://message-router.com.br/command-message", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dmoutinho.com.br.messagegateway.model;
